
//import java.text.NumberFormat;
import java.awt.event.KeyEvent;
import java.awt.print.PrinterException;
import static java.lang.Thread.sleep;
import java.sql.*;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import jxl.write.NumberFormat;
import net.proteanit.sql.DbUtils;

public class ProductSaleBill extends javax.swing.JFrame {

    PreparedStatement pst = null;
    ResultSet rs = null;
    Connection conn = null;
    int b_no=0;
    
    public ProductSaleBill() {
        initComponents();
        conn = connect.ConnectDB();
        setLocationRelativeTo(null);
        update_table();
        get_table();
        fillcombo();
        CurrentDate();
        billno();
    }

    private void update_table(){
        conn = connect.ConnectDB();
     try{
    String sql = "select * from final_bill";
         
     pst = conn.prepareStatement(sql);
     rs =pst.executeQuery();
     table_final_bill.setModel(DbUtils.resultSetToTableModel(rs));
     
     }
     catch(Exception e){
     JOptionPane.showMessageDialog(null, e);
     }
        
    }
    
    private void fillcombo(){
     //conn = connect.ConnectDB();
     try{
     String sql = "select customer_idno,customer_name,cellphone_number from customer_master";
         
     pst = conn.prepareStatement(sql);
     rs =pst.executeQuery();
     
     while(rs.next()){
     String name =rs.getString("customer_name");
     combo_box.addItem(name);
     }
     }
     catch(Exception e){
     JOptionPane.showMessageDialog(null, e);
     }
        
    }
     public void billno(){

        conn=connect.ConnectDB();
    try{
    String str = String.format("%04d", b_no);
    String sql ="select max(bill_no) from bill_info ";
    pst =conn.prepareStatement(sql);
    rs = pst.executeQuery();
    
    while(rs.next())
    {  
        if(rs!=null)
        {
            b_no=rs.getInt(1);
            b_no++;   
        }
        else if (rs==null)
        {
             b_no=101;
        }
    }
              txt_bill_no.setText(""+b_no);
              txt_bill_no.setEditable(false); 
    }
    
           catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
        }
    }
    
   
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        t = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txt_bill_no = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_customer_idno = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_cellphone_number = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_date = new javax.swing.JTextField();
        combo_box = new javax.swing.JComboBox();
        txt_customer_name = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txt_total_price = new javax.swing.JTextField();
        txt_price_per_kg = new javax.swing.JTextField();
        txt_bale_kgs = new javax.swing.JTextField();
        txt_item_srno = new javax.swing.JTextField();
        txt_item_type = new javax.swing.JTextField();
        txt_item_name = new javax.swing.JTextField();
        txt_item_no = new javax.swing.JTextField();
        cmd_add = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_item_bales = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        txt_item_search = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_select_item = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_final_bill = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        txt_total = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txt_subtotal = new javax.swing.JTextField();
        cmd_delete = new javax.swing.JButton();
        txt_tax = new javax.swing.JTextField();
        txt_taxv = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        cmd_print = new javax.swing.JButton();
        cmd_new = new javax.swing.JButton();
        cmd_save = new javax.swing.JButton();
        cmd_exit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 102));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel4.setBackground(new java.awt.Color(255, 204, 153));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Product Sale Bill", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.ABOVE_TOP, null, new java.awt.Color(0, 0, 0)));

        jPanel2.setBackground(new java.awt.Color(255, 204, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Customer Detail", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, null, new java.awt.Color(0, 0, 0)));

        jLabel1.setText("Bill No");

        jLabel2.setText("Bill To");

        jLabel3.setText("Customer RegNo");

        jLabel4.setText("Cellphone Number");

        jLabel6.setText("Date");

        combo_box.setBackground(new java.awt.Color(51, 102, 0));
        combo_box.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                combo_boxMouseClicked(evt);
            }
        });
        combo_box.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                combo_boxPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jLabel18.setText("Customer Name ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_bill_no, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(jLabel2)
                .addGap(32, 32, 32)
                .addComponent(combo_box, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(txt_customer_idno, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_customer_name, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(txt_cellphone_number, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(txt_date, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_customer_idno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(txt_bill_no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(txt_cellphone_number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txt_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_customer_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 204, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Item Details", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, null, new java.awt.Color(0, 0, 0)));
        jPanel3.setForeground(new java.awt.Color(51, 102, 0));

        txt_price_per_kg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_price_per_kgActionPerformed(evt);
            }
        });

        cmd_add.setBackground(new java.awt.Color(153, 0, 0));
        cmd_add.setForeground(new java.awt.Color(255, 255, 255));
        cmd_add.setText("ADD");
        cmd_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_addActionPerformed(evt);
            }
        });

        jLabel7.setText("Total Price");

        jLabel8.setText("Price Per Kg");

        jLabel9.setText("Bale Kgs");

        jLabel10.setText("Item Bales");

        jLabel11.setText("Item Srno");

        jLabel12.setText("Item Type");

        jLabel13.setText("Item No");

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Item Name");

        txt_item_bales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_item_balesActionPerformed(evt);
            }
        });
        txt_item_bales.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_item_balesKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_item_balesKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_item_no, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_item_name, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(59, 59, 59)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_item_type, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(60, 60, 60)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(txt_item_srno, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(txt_item_bales, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_bale_kgs, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(52, 52, 52)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_price_per_kg, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(52, 52, 52)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txt_total_price, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(cmd_add))
                    .addComponent(jLabel7)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel13))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_total_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_price_per_kg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_bale_kgs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_item_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_item_no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmd_add))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_item_srno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_item_bales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txt_item_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(255, 204, 0));
        jPanel6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel7.setBackground(new java.awt.Color(255, 204, 153));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Select Items", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, null, new java.awt.Color(0, 0, 0)));

        jLabel14.setText("Search");

        txt_item_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_item_searchKeyReleased(evt);
            }
        });

        table_select_item.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table_select_item.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_select_itemMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table_select_item);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel14)
                .addGap(30, 30, 30)
                .addComponent(txt_item_search, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txt_item_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel8.setBackground(new java.awt.Color(255, 204, 153));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Final Bill", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, null, new java.awt.Color(0, 0, 0)));

        table_final_bill.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table_final_bill.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_final_billMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_final_bill);

        jLabel15.setText("Tax");

        jLabel16.setText("Total");

        jLabel17.setText("SubTotal");

        txt_subtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_subtotalActionPerformed(evt);
            }
        });

        cmd_delete.setBackground(new java.awt.Color(153, 0, 0));
        cmd_delete.setForeground(new java.awt.Color(255, 255, 255));
        cmd_delete.setText("DELETE");
        cmd_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_deleteActionPerformed(evt);
            }
        });

        txt_taxv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_taxvActionPerformed(evt);
            }
        });
        txt_taxv.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_taxvKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(cmd_delete)
                .addGap(62, 62, 62)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addComponent(txt_subtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jLabel15)
                .addGap(43, 43, 43)
                .addComponent(txt_taxv, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_tax, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                .addGap(40, 40, 40)
                .addComponent(jLabel16)
                .addGap(32, 32, 32)
                .addComponent(txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel17)
                    .addComponent(txt_subtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmd_delete)
                    .addComponent(txt_tax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_taxv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        cmd_print.setBackground(new java.awt.Color(153, 0, 0));
        cmd_print.setForeground(new java.awt.Color(255, 255, 255));
        cmd_print.setText("PRINT");
        cmd_print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_printActionPerformed(evt);
            }
        });

        cmd_new.setBackground(new java.awt.Color(153, 0, 0));
        cmd_new.setForeground(new java.awt.Color(255, 255, 255));
        cmd_new.setText("NEW");
        cmd_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_newActionPerformed(evt);
            }
        });

        cmd_save.setBackground(new java.awt.Color(153, 0, 0));
        cmd_save.setForeground(new java.awt.Color(255, 255, 255));
        cmd_save.setText("SAVE");
        cmd_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_saveActionPerformed(evt);
            }
        });

        cmd_exit.setBackground(new java.awt.Color(153, 0, 0));
        cmd_exit.setForeground(new java.awt.Color(255, 255, 255));
        cmd_exit.setText("EXIT");
        cmd_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_exitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(cmd_print)
                        .addGap(52, 52, 52)
                        .addComponent(cmd_new)
                        .addGap(47, 47, 47)
                        .addComponent(cmd_save)
                        .addGap(48, 48, 48)
                        .addComponent(cmd_exit)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmd_print)
                    .addComponent(cmd_new)
                    .addComponent(cmd_save)
                    .addComponent(cmd_exit)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_price_per_kgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_price_per_kgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_price_per_kgActionPerformed

    private void txt_item_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_item_searchKeyReleased
        // TODO add your handling code here:
         try{
            String sql ="select * from item_master where item_name =?";
            pst = conn.prepareStatement(sql);
            pst.setString(1,txt_item_search.getText());
            rs = pst.executeQuery();

            if(rs.next()){
             String add1 =rs.getString("item_no");
             txt_item_no.setText(add1);
             String add2 =rs.getString("item_name");
             txt_item_name.setText(add2);
             String add3 =rs.getString("item_type");
             txt_item_type.setText(add3);
             String add4 =rs.getString("item_srno");
             txt_item_srno.setText(add4);
            // String add5 =rs.getString("item_bales");
             //txt_item_bales.setText(add5);
             String add5 =rs.getString("bale_kgs");
             txt_bale_kgs.setText(add5);
             String add6 =rs.getString("price_per_kg");
             txt_price_per_kg.setText(add6);
            }

        }

        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_txt_item_searchKeyReleased

    private void table_select_itemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_select_itemMouseClicked
        // TODO add your handling code here:
        try
        {

            int row = table_select_item.getSelectedRow();
            String Table_click=(table_select_item.getModel().getValueAt(row, 0).toString());

            String sql = "select * from item_master where item_no = '" + Table_click + "'";
            pst =conn.prepareStatement(sql);
            rs = pst.executeQuery();

            if(rs.next()){

                String add1 =rs.getString("item_no");
                txt_item_no.setText(add1);
                String add2 =rs.getString("item_name");
                txt_item_name.setText(add2);
                String add3 =rs.getString("item_type");
                txt_item_type.setText(add3);
                String add4 =rs.getString("item_srno");
                txt_item_srno.setText(add4);
               // String add5 =rs.getString("item_bales");
               // txt_item_bales.setText(add5);
                String add5 =rs.getString("bale_kgs");
                txt_bale_kgs.setText(add5);
                String add6 =rs.getString("price_per_kg");
                txt_price_per_kg.setText(add6);

            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_table_select_itemMouseClicked

   
    
    private void cmd_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_addActionPerformed
        // TODO add your handling code here:
              try{
        String sql="insert into final_bill (item_no,item_name,item_type,item_srno,item_bales,bale_kgs,price_per_kg,total_price) values (?,?,?,?,?,?,?,?)";
        pst = conn.prepareStatement(sql);
        
        pst.setString(1,txt_item_no.getText());
        pst.setString(2,txt_item_name.getText());
        pst.setString(3,txt_item_type.getText());
        pst.setString(4,txt_item_srno.getText());
        pst.setString(5,txt_item_bales.getText());
        pst.setString(6,txt_bale_kgs.getText());
        pst.setString(7,txt_price_per_kg.getText());
        pst.setString(8,txt_total_price.getText());
        pst.execute();
        
        JOptionPane.showMessageDialog(null, "item added succesfully");
        txt_item_no.setText("");
        txt_item_name.setText("");
        txt_item_type.setText("");
        txt_item_srno.setText("");
        txt_item_bales.setText("");
        txt_bale_kgs.setText("");
        txt_price_per_kg.setText("");
        txt_total_price.setText("");  
        
          int tot =0;
          Statement stmt = conn.createStatement();     
          String sql1="Select total_price from final_bill";
          rs=stmt.executeQuery(sql1); 
           while(rs.next())
             {
           tot=tot+rs.getInt(1);
           }
            txt_subtotal.setText(""+tot);
            txt_tax.setFocusable(true);
          
          
          
          
              }
       
        catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
        }
        update_table();
    }//GEN-LAST:event_cmd_addActionPerformed

     public void CurrentDate()
     {
     Thread clock = new Thread(){
         @Override
    public void run(){
    for(;;){
         
    Calendar cal = new GregorianCalendar();
    int month = cal.get(Calendar.MONTH);
    int year = cal.get(Calendar.YEAR);
    int day = cal.get(Calendar.DAY_OF_MONTH);
    
    int second = cal.get(Calendar.SECOND);
    int minute = cal.get(Calendar.MINUTE);
    int hour = cal.get(Calendar.HOUR);
    txt_date.setText((year + "-" + (month + 1) + "-" + day) +"  "+ (hour + ":" + (minute) + ":" + second));
   
    try {
    sleep(1000);
    }
    catch(InterruptedException ex)
    {
    Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE,null,ex);
    }
    }    
    }
    };
    clock.start();
    }
    private void cmd_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_saveActionPerformed
        // TODO add your handling code here:
        
        try{
        String sql="insert into bill_info(date,bill_no,customer_idno,customer_name,cellphone_number,subtotal,tax,total) values (?,?,?,?,?,?,?,?)";
        pst = conn.prepareStatement(sql);
        
        pst.setString(1,txt_date.getText());
        pst.setString(2,txt_bill_no.getText());
        pst.setString(3,txt_customer_idno.getText());
        pst.setString(4,txt_customer_name.getText());
        pst.setString(5,txt_cellphone_number.getText());
        pst.setString(6,txt_subtotal.getText());
        pst.setString(7,txt_tax.getText());
        pst.setString(8,txt_total.getText());
        pst.execute();
        
        JOptionPane.showMessageDialog(null, "sale saved succesfully");
        txt_bill_no.setText("");
        txt_customer_idno.setText("");
        txt_customer_name.setText("");
        txt_cellphone_number.setText("");
        txt_date.setText("");
        txt_subtotal.setText("");
        txt_tax.setText("");
        txt_total.setText("");
          
        String sql1 ="delete from final_bill";
        pst=conn.prepareStatement(sql1);
        pst.execute();
        conn.close();
    
        }
        
        catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
        }
        update_table();
       
             try {
            String sql ="select max(bill_no) from bill_info";
            pst =conn.prepareStatement(sql);
            rs = pst.executeQuery();
       if(rs.next())
              {
                       b_no= rs.getInt(1);
                     b_no++;
              }
              txt_bill_no.setText(""+b_no);
 } catch(Exception e){
     JOptionPane.showMessageDialog(null, e);
        } 
    }//GEN-LAST:event_cmd_saveActionPerformed

    private void combo_boxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_combo_boxMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_boxMouseClicked

    private void combo_boxPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_combo_boxPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
         String tmp = (String)combo_box.getSelectedItem();
         String sql = "select customer_idno,customer_name,cellphone_number from customer_master where customer_name =?";
         try{
            pst = conn.prepareStatement(sql);
            pst.setString(1,tmp);
            rs = pst.executeQuery();

            if(rs.next()){
             String add1 =rs.getString("customer_idno");
             txt_customer_idno.setText(add1);
             String add2 =rs.getString("customer_name");
             txt_customer_name.setText(add2);
             String add3 =rs.getString("cellphone_number");
             txt_cellphone_number.setText(add3);
            }
   
     }
     catch(Exception e){
     JOptionPane.showMessageDialog(null, e);
     }
        
    }//GEN-LAST:event_combo_boxPopupMenuWillBecomeInvisible

    private void cmd_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_deleteActionPerformed
        // TODO add your handling code here:
         int q =JOptionPane.showConfirmDialog(null, "Do you really want to delete","Delete",JOptionPane.YES_NO_OPTION);
        if (q == 0);{
            String sql ="Delete from final_bill where item_no =?";
            try{
                pst =conn.prepareStatement(sql);
                pst.setString(1,txt_item_no.getText());
                pst.execute();

                JOptionPane.showMessageDialog(null, "Entry successfully deleted");
                  txt_item_no.setText("");
                  txt_item_name.setText("");
                  txt_item_type.setText("");
                  txt_item_srno.setText("");
                  txt_item_bales.setText("");
                  txt_bale_kgs.setText("");
                  txt_price_per_kg.setText("");
                  txt_total_price.setText(""); 
            }

            catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
            update_table();
        }
    }//GEN-LAST:event_cmd_deleteActionPerformed

    private void table_final_billMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_final_billMouseClicked
        // TODO add your handling code here:
      try
        {
        
        int row = table_final_bill.getSelectedRow();
        String Table_click=(table_final_bill.getModel().getValueAt(row, 0).toString());
         
        String sql = "select * from final_bill where item_no = '" + Table_click + "'";
        pst =conn.prepareStatement(sql);
        rs = pst.executeQuery();
         
         if(rs.next()){
         
             String add1 =rs.getString("item_no");
             txt_item_no.setText(add1);
             String add2 =rs.getString("item_name");
             txt_item_name.setText(add2);
             String add3 =rs.getString("item_type");
             txt_item_type.setText(add3);
             String add4 =rs.getString("item_srno");
             txt_item_srno.setText(add4);
             String add5 =rs.getString("item_bales");
             txt_item_bales.setText(add5);
             String add6 =rs.getString("bale_kgs");
             txt_bale_kgs.setText(add6);
             String add7 =rs.getString("price_per_kg");
             txt_price_per_kg.setText(add7);
             String add8 =rs.getString("total_price");
             txt_price_per_kg.setText(add8);
        }        
        }
        catch(Exception e)
                {
        JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_table_final_billMouseClicked

    private void txt_item_balesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_item_balesActionPerformed
        // TODO add your handling code here:    
    }//GEN-LAST:event_txt_item_balesActionPerformed

    private void txt_item_balesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_item_balesKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_item_balesKeyTyped

    private void txt_item_balesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_item_balesKeyReleased
        // TODO add your handling code here:
   
          double add1 = Double.parseDouble(txt_bale_kgs.getText());
          double add2 = Double.parseDouble(txt_price_per_kg.getText());
          double add = Double.parseDouble(txt_item_bales.getText());
          double add3= (add * add1 * add2);
          String add4= Double.toString(add3);
          txt_total_price.setText(add4);
          
         
    }//GEN-LAST:event_txt_item_balesKeyReleased

    private void cmd_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_newActionPerformed
        // TODO add your handling code here:
        txt_bill_no.setText("");
        txt_customer_idno.setText("");
        txt_customer_name.setText("");
        txt_cellphone_number.setText("");
        txt_date.setText("");
        txt_item_no.setText("");
        txt_item_name.setText("");
        txt_item_type.setText("");
        txt_item_srno.setText("");
        txt_item_bales.setText("");
        txt_bale_kgs.setText("");
        txt_price_per_kg.setText("");
        txt_total_price.setText("");
        txt_subtotal.setText("");
        txt_tax.setText("");
        txt_total.setText("");
        
             try {
            String sql ="select max(bill_no) from bill_info";
            pst =conn.prepareStatement(sql);
            rs = pst.executeQuery();
       if(rs.next())
              {
                       b_no= rs.getInt(1);
                     b_no++;
              }
              txt_bill_no.setText(""+b_no);
 } catch(Exception e){
     JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_cmd_newActionPerformed

    private void cmd_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_exitActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_cmd_exitActionPerformed

    private void txt_taxvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_taxvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_taxvActionPerformed

    private void txt_taxvKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_taxvKeyReleased
        // TODO add your handling code here:
       
          double add5 = Double.parseDouble(txt_subtotal.getText());
          double add6 = Double.parseDouble(txt_taxv.getText());
          double perValue =0;
          perValue =(((add5 ) * (add6/100)));
          txt_tax.setText(""+perValue);
          double add7 =add5 + perValue ;
          String add8= Double.toString(add7);
          txt_total.setText(add8);
    }//GEN-LAST:event_txt_taxvKeyReleased

    private void txt_subtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_subtotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_subtotalActionPerformed

    private void cmd_printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_printActionPerformed
        // TODO add your handling code here:
        try{
           boolean complete = table_select_item.print();
           if(complete){
           JOptionPane.showMessageDialog(null, "DONE PRINTING","INFORMATION",JOptionPane.INFORMATION_MESSAGE);
           }
           else{
           JOptionPane.showMessageDialog(null,"EXITING PRINTING","PRINTER",JOptionPane.ERROR_MESSAGE);
           }
        }
        catch(PrinterException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_cmd_printActionPerformed

     
     private void get_table(){
     conn = connect.ConnectDB();
     try{
    String sql = "select * from item_master";
         
     pst = conn.prepareStatement(sql);
     rs =pst.executeQuery();
     table_select_item.setModel(DbUtils.resultSetToTableModel(rs));
     
     }
     catch(Exception e){
     JOptionPane.showMessageDialog(null, e);
     }
        
    }
    
    
   
    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductSaleBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductSaleBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductSaleBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductSaleBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ProductSaleBill().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmd_add;
    private javax.swing.JButton cmd_delete;
    private javax.swing.JButton cmd_exit;
    private javax.swing.JButton cmd_new;
    private javax.swing.JButton cmd_print;
    private javax.swing.JButton cmd_save;
    private javax.swing.JComboBox combo_box;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField t;
    private javax.swing.JTable table_final_bill;
    private javax.swing.JTable table_select_item;
    private javax.swing.JTextField txt_bale_kgs;
    private javax.swing.JTextField txt_bill_no;
    private javax.swing.JTextField txt_cellphone_number;
    private javax.swing.JTextField txt_customer_idno;
    private javax.swing.JTextField txt_customer_name;
    private javax.swing.JTextField txt_date;
    private javax.swing.JTextField txt_item_bales;
    private javax.swing.JTextField txt_item_name;
    private javax.swing.JTextField txt_item_no;
    private javax.swing.JTextField txt_item_search;
    private javax.swing.JTextField txt_item_srno;
    private javax.swing.JTextField txt_item_type;
    private javax.swing.JTextField txt_price_per_kg;
    private javax.swing.JTextField txt_subtotal;
    private javax.swing.JTextField txt_tax;
    private javax.swing.JTextField txt_taxv;
    private javax.swing.JTextField txt_total;
    private javax.swing.JTextField txt_total_price;
    // End of variables declaration//GEN-END:variables
}
