
//import java.awt.HeadlessException;
import java.sql.*;
import javax.swing.*;
public class UserRegistration extends javax.swing.JFrame {

Connection con=null;
ResultSet rs=null;
PreparedStatement pst=null;
    
    public UserRegistration() {
        initComponents();
        con = connect.ConnectDB();
        setLocationRelativeTo(null);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_full_name = new javax.swing.JTextField();
        txt_user_name = new javax.swing.JTextField();
        txt_contact = new javax.swing.JTextField();
        txt_reg_no = new javax.swing.JTextField();
        txt_email_id = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_password = new javax.swing.JPasswordField();
        txt_confirm_password = new javax.swing.JPasswordField();
        jPanel3 = new javax.swing.JPanel();
        cmd_new = new javax.swing.JButton();
        cmd_save = new javax.swing.JButton();
        cmd_update = new javax.swing.JButton();
        cmd_delete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "User Registration", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, null, new java.awt.Color(0, 0, 0)));

        jPanel2.setBackground(new java.awt.Color(255, 204, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "User Details", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, null, new java.awt.Color(0, 0, 0)));

        jLabel1.setText("Name");

        jLabel2.setText("User Name");

        jLabel3.setText("Password");

        jLabel4.setText("Contact");

        jLabel5.setText("Email Id");

        jLabel6.setText("Reg No");

        jLabel7.setText("Confirm Password");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_full_name)
                    .addComponent(txt_user_name)
                    .addComponent(txt_contact)
                    .addComponent(txt_reg_no)
                    .addComponent(txt_email_id)
                    .addComponent(txt_password)
                    .addComponent(txt_confirm_password, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_full_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_user_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_confirm_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_contact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_reg_no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(txt_email_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 204, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        cmd_new.setBackground(new java.awt.Color(153, 0, 0));
        cmd_new.setForeground(new java.awt.Color(255, 255, 255));
        cmd_new.setText("NEW");
        cmd_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_newActionPerformed(evt);
            }
        });

        cmd_save.setBackground(new java.awt.Color(153, 0, 0));
        cmd_save.setForeground(new java.awt.Color(255, 255, 255));
        cmd_save.setText("SAVE");
        cmd_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_saveActionPerformed(evt);
            }
        });

        cmd_update.setBackground(new java.awt.Color(153, 0, 0));
        cmd_update.setForeground(new java.awt.Color(255, 255, 255));
        cmd_update.setText("UPDATE");
        cmd_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_updateActionPerformed(evt);
            }
        });

        cmd_delete.setBackground(new java.awt.Color(153, 0, 0));
        cmd_delete.setForeground(new java.awt.Color(255, 255, 255));
        cmd_delete.setText("DELETE");
        cmd_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_deleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmd_new, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmd_save, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmd_update, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                    .addComponent(cmd_delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(cmd_new)
                .addGap(65, 65, 65)
                .addComponent(cmd_save)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cmd_update)
                .addGap(72, 72, 72)
                .addComponent(cmd_delete)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmd_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_newActionPerformed
        // TODO add your handling code here:
        txt_full_name.setText("");
        txt_user_name.setText("");
        txt_password.setText("");
        txt_confirm_password.setText("");
        txt_contact.setText("");
        txt_reg_no.setText("");
        txt_email_id.setText("");
    }//GEN-LAST:event_cmd_newActionPerformed

    private void cmd_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_updateActionPerformed
        // TODO add your handling code here:
           if (txt_full_name.getText().equals("")) {
           JOptionPane.showMessageDialog( this, "Please enter full name","Error", JOptionPane.ERROR_MESSAGE);
           return;
            }
        if (txt_user_name.getText().equals("")) {
           JOptionPane.showMessageDialog( this, "Please enter user name","Error", JOptionPane.ERROR_MESSAGE);
           return;
            }
        
        String Password= String.valueOf(txt_password.getPassword());
         if (Password.equals("")) {
           JOptionPane.showMessageDialog( this, "Please enter password","Error", JOptionPane.ERROR_MESSAGE);
           return;
            }
         if (Password.length()< 8) {
               
                JOptionPane.showMessageDialog(this,
                                         "The Password Should be of Atleast 8 Characters",
                                         "Error", JOptionPane.ERROR_MESSAGE);
                return;
               }
        String ConfirmPassword=String.valueOf(txt_confirm_password.getPassword());
          if (ConfirmPassword.equals("")){
           JOptionPane.showMessageDialog( this, "Please enter confirm password." ,"Error", JOptionPane.ERROR_MESSAGE);
           return;
            }
          if (ConfirmPassword.length()< 8) {
               
                JOptionPane.showMessageDialog(this,
                                         "The Password Should be of Atleast 8 Characters",
                                         "Error", JOptionPane.ERROR_MESSAGE);
                return;
               }
          
           if (!(Password).equals(ConfirmPassword)) {
               
                JOptionPane.showMessageDialog(this,
                                         "Password doesn't match with Confirmed Password",
                                         "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
          
          if (txt_contact.getText().equals("")) {
           JOptionPane.showMessageDialog( this, "Please enter contact","Error", JOptionPane.ERROR_MESSAGE);
           return;
            }
          
           
        if (txt_reg_no.getText().equals("")) {
           JOptionPane.showMessageDialog( this, "Please enter reg no","Error", JOptionPane.ERROR_MESSAGE);
           return;
            }
        
       
        
          if (txt_email_id.getText().equals("")) {
           JOptionPane.showMessageDialog( this, "Please enter email id","Error", JOptionPane.ERROR_MESSAGE);
           return;
            }
          
         try{
             
             
  
              Statement stmt;
              stmt= con.createStatement();
              
              //maintain same password during update
              
              String sql8="Select password from user_registration where password= '" + txt_password.getText() + "'";
              rs=stmt.executeQuery(sql8);
              if(!(rs.next())){
              JOptionPane.showMessageDialog( this, "Sorry wrong password","Error", JOptionPane.ERROR_MESSAGE);
              txt_password.setText("");
              txt_password.requestDefaultFocus();
              return; 
              }
              //dont update reg_no
              
              String sql9="Select reg_no from user_registration where reg_no= '" + txt_reg_no.getText() + "'";
              rs=stmt.executeQuery(sql9);
              if(!(rs.next())){
              JOptionPane.showMessageDialog( this, "Sorry This Reg No Doesn't exists","Error", JOptionPane.ERROR_MESSAGE);
              txt_reg_no.setText("");
              txt_reg_no.requestDefaultFocus();
              return; 
              }
              
            String value1 = txt_full_name.getText();
            String value2 = txt_user_name.getText();
            String value3 = txt_password.getText();
            String value4 = txt_confirm_password.getText();
            String value5 = txt_contact.getText();
            String value6 = txt_reg_no.getText();
            String value7 = txt_email_id.getText();
            
            String sql ="update user_registration set full_name='"+value1+"',user_name='"+value2+"',password='"+value3+"',confirm_password='"+value4+"',contact='"+value5+"',reg_no='"+value6+"',email_id='"+value7+"' where reg_no='"+value6+"'";
            pst=con.prepareStatement(sql);
            pst.execute();
            
            String sql1 ="update login_info set user_name='"+value2+"',password='"+value3+"',reg_no='"+value6+"' where reg_no='"+value6+"'";
            pst=con.prepareStatement(sql1);
            pst.execute();
            
        JOptionPane.showMessageDialog(null, "Updated successfully");
        txt_full_name.setText("");
        txt_user_name.setText("");
        txt_password.setText("");
        txt_confirm_password.setText("");
        txt_contact.setText("");
        txt_reg_no.setText("");
        txt_email_id.setText("");
        
        }
        catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_cmd_updateActionPerformed

    private void cmd_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_deleteActionPerformed
        // TODO add your handling code here:
            
        if (txt_reg_no.getText().equals("")) {
           JOptionPane.showMessageDialog( this, "Please enter reg no","Error", JOptionPane.ERROR_MESSAGE);
           return;
            }
        
         int q =JOptionPane.showConfirmDialog(null, "Do you really want to delete","Delete",JOptionPane.YES_NO_OPTION);
        if (q == 0);{
        
           
            try{
                
              Statement stmt;
              stmt= con.createStatement();
              String sql8="Select reg_no from user_registration where reg_no= '" + txt_reg_no.getText() + "'";
              rs=stmt.executeQuery(sql8);
              if(!(rs.next())){
              JOptionPane.showMessageDialog( this, "Sorry This Reg No Doesn't exist","Error", JOptionPane.ERROR_MESSAGE);
              txt_reg_no.setText("");
              txt_reg_no.requestDefaultFocus();
              return; 
              }
                
            String sql ="Delete from user_registration where reg_no =?"; 
                pst =con.prepareStatement(sql);
                pst.setString(1,txt_reg_no.getText());
                pst.execute();
                
             String sql1 ="Delete from login_info where reg_no =?";
             
                pst =con.prepareStatement(sql1);
                pst.setString(1,txt_reg_no.getText());
                pst.execute();
             
                JOptionPane.showMessageDialog(null, "User deleted successfully");
                  txt_full_name.setText("");
                  txt_user_name.setText("");
                  txt_password.setText("");
                  txt_confirm_password.setText("");
                  txt_contact.setText("");
                  txt_reg_no.setText("");
                  txt_email_id.setText("");

            }

        catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
            
        }
    }//GEN-LAST:event_cmd_deleteActionPerformed

    private void cmd_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_saveActionPerformed
        // TODO add your handling code here:
          
           
             
         if (txt_full_name.getText().equals("")) {
           JOptionPane.showMessageDialog( this, "Please enter full name","Error", JOptionPane.ERROR_MESSAGE);
           return;
            }
        if (txt_user_name.getText().equals("")) {
           JOptionPane.showMessageDialog( this, "Please enter user name","Error", JOptionPane.ERROR_MESSAGE);
           return;
            }
        
        String Password= String.valueOf(txt_password.getPassword());
         if (Password.equals("")) {
           JOptionPane.showMessageDialog( this, "Please enter password","Error", JOptionPane.ERROR_MESSAGE);
           return;
            }
         if (Password.length()< 8) {
               
                JOptionPane.showMessageDialog(this,
                                         "The Password Should be of Atleast 8 Characters",
                                         "Error", JOptionPane.ERROR_MESSAGE);
                return;
               }
        String ConfirmPassword=String.valueOf(txt_confirm_password.getPassword());
          if (ConfirmPassword.equals("")){
           JOptionPane.showMessageDialog( this, "Please enter confirm password." ,"Error", JOptionPane.ERROR_MESSAGE);
           return;
            }
          if (ConfirmPassword.length()< 8) {
               
                JOptionPane.showMessageDialog(this,
                                         "The Password Should be of Atleast 8 Characters",
                                         "Error", JOptionPane.ERROR_MESSAGE);
                return;
               }
          
           if (!(Password).equals(ConfirmPassword)) {
               
                JOptionPane.showMessageDialog(this,
                                         "Password doesn't match with Confirmed Password",
                                         "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
          
          if (txt_contact.getText().equals("")) {
           JOptionPane.showMessageDialog( this, "Please enter contact","Error", JOptionPane.ERROR_MESSAGE);
           return;
            }
         
           
        if (txt_reg_no.getText().equals("")) {
           JOptionPane.showMessageDialog( this, "Please enter reg no","Error", JOptionPane.ERROR_MESSAGE);
           return;
            }
          if (txt_email_id.getText().equals("")) {
           JOptionPane.showMessageDialog( this, "Please enter email id","Error", JOptionPane.ERROR_MESSAGE);
           return;
            }
          
      
          try{
              
         
              Statement stmt;
              stmt= con.createStatement();
              
              String sql1="Select user_name from user_registration where user_name= '" + txt_user_name.getText() + "'";
              rs=stmt.executeQuery(sql1);
              if(rs.next()){
              JOptionPane.showMessageDialog( this, "User Name already exists","Error", JOptionPane.ERROR_MESSAGE);
              txt_user_name.setText("");
              txt_user_name.requestDefaultFocus();
              return;    
       }
             
              
              String sql4="Select password from user_registration where password= '" + txt_password.getText() + "'";
              rs=stmt.executeQuery(sql4);
              if(rs.next()){
              JOptionPane.showMessageDialog( this, "Sorry Please try a Stronger password","Error", JOptionPane.ERROR_MESSAGE);
              txt_password.setText("");
              txt_password.requestDefaultFocus();
              return;    
       }
              
              
              String sql3="Select contact from user_registration where contact= '" + txt_contact.getText() + "'";
              rs=stmt.executeQuery(sql3);
              if(rs.next()){
              JOptionPane.showMessageDialog( this, "Contact already exists","Error", JOptionPane.ERROR_MESSAGE);
              txt_contact.setText("");
              txt_contact.requestDefaultFocus();
              return;    
       }
              
              String sql5="Select reg_no from user_registration where reg_no= '" + txt_reg_no.getText() + "'";
              rs=stmt.executeQuery(sql5);
              if(rs.next()){
              JOptionPane.showMessageDialog( this, "Reg No already exists","Error", JOptionPane.ERROR_MESSAGE);
              txt_reg_no.setText("");
              txt_reg_no.requestDefaultFocus();
              return;    
       }
           
              
       String Password1= String.valueOf(txt_password.getPassword());     
       String sql= "insert into user_registration(full_name,user_name,password,confirm_password,contact,reg_no,email_id)values('"+ txt_full_name.getText() + "','"+ txt_user_name.getText() + "','" + Password1 + "','" + txt_confirm_password.getText() + "','" + txt_contact.getText() + "','" + txt_reg_no.getText() + "','" + txt_email_id.getText() + "')";
      
      pst=con.prepareStatement(sql);
      pst.execute();
      String sql2= "insert into login_info(user_name,password,reg_no)values('" + txt_user_name.getText() + "','" + Password1 + "','" + txt_reg_no.getText() + "')";
      
      pst=con.prepareStatement(sql2);
      pst.execute();
      JOptionPane.showMessageDialog(this,"Successfully Registered" ,"User",JOptionPane.INFORMATION_MESSAGE); 
        txt_full_name.setText("");
        txt_user_name.setText("");
        txt_password.setText("");
        txt_confirm_password.setText("");
        txt_contact.setText("");
        txt_reg_no.setText("");
        txt_email_id.setText("");
              
          
        }
        
         
        
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
    }//GEN-LAST:event_cmd_saveActionPerformed
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
           @Override
            public void run() {
                new UserRegistration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmd_delete;
    private javax.swing.JButton cmd_new;
    private javax.swing.JButton cmd_save;
    private javax.swing.JButton cmd_update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField txt_confirm_password;
    private javax.swing.JTextField txt_contact;
    private javax.swing.JTextField txt_email_id;
    private javax.swing.JTextField txt_full_name;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_reg_no;
    private javax.swing.JTextField txt_user_name;
    // End of variables declaration//GEN-END:variables
}
